server.port=8888
spring.application.name=config-service

# Repo de configuraciones
spring.cloud.config.server.git.uri=https://github.com/salakin93/microservices-config
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main