server.port=8082
spring.application.name=document-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.datasource.url=jdbc:postgresql://localhost:5435/document_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info

file.storage.path=uploads

spring.servlet.multipart.max-file-size=35MB
spring.servlet.multipart.max-request-size=35MB