server.port=8080
spring.application.name=gateway-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

management.endpoints.web.exposure.include=health,info

spring.cloud.gateway.server.webflux.discovery.locator.enabled=false

# AUTH
spring.cloud.gateway.server.webflux.routes[0].id=identity-auth
spring.cloud.gateway.server.webflux.routes[0].uri=lb://identity-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/api/auth/(?<segment>.*), /v1/auth/$\{segment}

# ADMIN USERS exact root
spring.cloud.gateway.server.webflux.routes[1].id=identity-admin-users-root
spring.cloud.gateway.server.webflux.routes[1].uri=lb://identity-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/admin/users
spring.cloud.gateway.server.webflux.routes[1].filters[0]=SetPath=/v1/admin/users

# ADMIN USERS subpaths
spring.cloud.gateway.server.webflux.routes[2].id=identity-admin-users-subpath
spring.cloud.gateway.server.webflux.routes[2].uri=lb://identity-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/admin/users/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=RewritePath=/api/admin/users/(?<segment>.*), /v1/admin/users/$\{segment}