server.port=8081
spring.application.name=identity-service

spring.datasource.url=jdbc:postgresql://postgres:5432/identity_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false